// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CategoryButton: typeof import('./src/components/CategoryButton.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FunctionRow: typeof import('./src/components/FunctionRow.vue')['default']
    IIonHeart: typeof import('~icons/ion/heart')['default']
    IIonIosArrowUp: typeof import('~icons/ion/ios-arrow-up')['default']
    NavBarMenuDown: typeof import('./src/components/NavBarMenuDown.vue')['default']
    PcNavBar: typeof import('./src/components/PcNavBar.vue')['default']
    ProductBox: typeof import('./src/components/ProductBox.vue')['default']
  }
}

export { }
