// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CartProductRow: typeof import('./src/components/CartProductRow.vue')['default']
    CategoryMenu: typeof import('./src/components/CategoryMenu.vue')['default']
    CategoryMenuMobile: typeof import('./src/components/CategoryMenuMobile.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FunctionRow: typeof import('./src/components/FunctionRow.vue')['default']
    'ICarbon:arrowDown': typeof import('~icons/carbon/arrow-down')['default']
    IIcBaselineArrowDownward: typeof import('~icons/ic/baseline-arrow-downward')['default']
    IIcBaselineEmail: typeof import('~icons/ic/baseline-email')['default']
    IIcBaselinePhone: typeof import('~icons/ic/baseline-phone')['default']
    'IIon:cartOutline': typeof import('~icons/ion/cart-outline')['default']
    'IIon:homeOutline': typeof import('~icons/ion/home-outline')['default']
    'IIon:iosCloseEmpty': typeof import('~icons/ion/ios-close-empty')['default']
    'IIon:menuOutline': typeof import('~icons/ion/menu-outline')['default']
    'IIon:search': typeof import('~icons/ion/search')['default']
    'IPh:magnifyingGlass': typeof import('~icons/ph/magnifying-glass')['default']
    IPhMagnifyingGlassBold: typeof import('~icons/ph/magnifying-glass-bold')['default']
    IPhQuestion: typeof import('~icons/ph/question')['default']
    'IUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    MobileNavBar: typeof import('./src/components/MobileNavBar.vue')['default']
    NavBarMenuDown: typeof import('./src/components/NavBarMenuDown.vue')['default']
    PcNavBar: typeof import('./src/components/PcNavBar.vue')['default']
    ProductBox: typeof import('./src/components/ProductBox.vue')['default']
    ProductDetail: typeof import('./src/components/ProductDetail.vue')['default']
    RelatedProduct: typeof import('./src/components/RelatedProduct.vue')['default']
  }
}

export { }
